export const LOAD_CARDS = "CARDS/LOAD_CARDS";
export const LOAD_DATA = "DATA/LOAD_DATA";

export const MOVE_TO_CURRENT_POKEMON = "PAGE/MOVE_TO_CURRENT_POKEMON";

export const CATCH_POKEMON = "POKEMON/CATCH_POKEMON";
export const LETGO_POKEMON = "POKEMON/LETGO_POKEMON";
